name: 250518_RNA-seq_yeast_anaerobic_v_aerobic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - annotated-types=0.7.0
  - argcomplete=3.6.2
  - attrs=25.3.0
  - bioconductor-annotationdbi=1.68.0
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-data-packages=20250401
  - bioconductor-delayedarray=0.32.0
  - bioconductor-deseq2=1.46.0
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicranges=1.58.0
  - bioconductor-iranges=2.40.0
  - bioconductor-keggrest=1.46.0
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-org.sc.sgd.db=3.20.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-tximport=1.34.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - boost-cpp=1.85.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - cctools_osx-arm64=1010.6
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - clang=20.1.5
  - clang-20=20.1.5
  - clang_impl_osx-arm64=20.1.5
  - clang_osx-arm64=20.1.5
  - clangxx=20.1.5
  - clangxx_impl_osx-arm64=20.1.5
  - clangxx_osx-arm64=20.1.5
  - click=8.2.0
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - compiler-rt=20.1.5
  - compiler-rt_osx-arm64=20.1.5
  - curl=8.13.0
  - dart-sass=1.59.1
  - deno=1.46.3
  - deno-dom=0.1.41
  - esbuild=0.25.4
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gfortran_impl_osx-arm64=13.3.0
  - gfortran_osx-arm64=13.3.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - h2=4.2.0
  - harfbuzz=11.1.0
  - hpack=4.1.0
  - humanfriendly=10.0
  - humanize=4.12.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - isl=0.26
  - jinja2=3.1.6
  - jq=1.7.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - kaleido-core=0.2.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.5
  - libcurl=8.13.0
  - libcxx=20.1.5
  - libcxx-devel=20.1.5
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgff=2.0.0
  - libgfortran=14.2.0
  - libgfortran-devel_osx-arm64=13.3.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.24.1
  - libjemalloc=5.3.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - llvm-tools=20.1.5
  - llvm-tools-20=20.1.5
  - make=4.4.1
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mathjax=2.7.7
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - multiqc=1.28
  - narwhals=1.39.1
  - natsort=8.4.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - oniguruma=6.9.10
  - openjdk=23.0.2
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandoc=3.6.3
  - pango=1.56.3
  - pcre2=10.44
  - perl=5.32.1
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - plotly=6.1.0
  - pthread-stubs=0.4
  - pyaml-env=1.2.2
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.13.3
  - python-dotenv=1.1.0
  - python-kaleido=0.2.1
  - python_abi=3.13
  - pyyaml=6.0.2
  - quarto=1.7.31
  - r-abind=1.4_5
  - r-aplot=0.2.5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.2
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-broom=1.0.8
  - r-broom.helpers=1.21.0
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cards=0.6.0
  - r-cellranger=1.1.0
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-colourpicker=1.3.0
  - r-commonmark=1.9.5
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crul=1.5.0
  - r-curl=6.2.2
  - r-data.table=1.17.2
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.3
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-flextable=0.9.8
  - r-fontawesome=0.5.3
  - r-fontbitstreamvera=0.1.1
  - r-fontliberation=0.1.0
  - r-fontquiver=0.2.1
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gargle=1.5.2
  - r-gdtools=0.4.0
  - r-generics=0.1.4
  - r-gfonts=0.2.0
  - r-ggally=2.2.1
  - r-ggbreak=0.1.4
  - r-ggextra=0.10.1
  - r-ggfun=0.1.8
  - r-ggplot2=3.5.2
  - r-ggplotify=0.1.2
  - r-ggridges=0.5.6
  - r-ggstats=0.9.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gridgraphics=0.5_1
  - r-gtable=0.3.6
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=1.1.2
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kableextra=1.4.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-labelled=2.14.1
  - r-lambda.r=1.2.4
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lifecycle=1.0.4
  - r-locfit=1.5_9.12
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-officer=0.6.9
  - r-openssl=2.3.2
  - r-patchwork=1.3.0
  - r-pillar=1.10.2
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.3
  - r-promises=1.3.2
  - r-ps=1.9.1
  - r-purrr=1.0.4
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.14
  - r-rcpparmadillo=14.4.2_1
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rsqlite=2.3.11
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-shiny=1.10.0
  - r-shinyjs=2.1.0
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-svglite=2.1.3
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-textshaping=1.0.1
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.57
  - r-triebeard=0.4.1
  - r-tzdb=0.5.0
  - r-urltools=1.7.3
  - r-utf8=1.2.5
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-webshot=0.5.5
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-yulab.utils=0.2.0
  - r-zip=2.3.3
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=14.0.0
  - rich-click=1.8.8
  - rpds-py=0.25.0
  - salmon=1.10.3
  - setuptools=80.8.0
  - sigtool=0.1.3
  - spectra=0.0.11
  - staden_io_lib=1.15.0
  - tapi=1300.6.5
  - tbb=2022.1.0
  - tiktoken=0.9.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.13.2
  - tqdm=4.67.1
  - trimmomatic=0.39
  - typeguard=4.4.2
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - typst=0.13.0
  - tzdata=2025b
  - urllib3=2.4.0
  - wget=1.21.4
  - xmltodict=0.14.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yq=3.4.3
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
